let movies = [
    {
        id: 1,
        title: "Matrix Recargado",
        rating: 7,
        awards: 5,
        length: 120,
        price: 100,
        genre: "Acción",
    },
    {
        id: 2,
        title: "Harry Potter y la piedra filosofal",
        rating: 8,
        awards: 7,
        length: 120,
        price: 120,
        genre: "Aventuras",
    },
    {
        id: 3,
        title: "Kill Bill 2",
        rating: 9,
        awards: 3,
        length: 145,
        price: 90,
        genre: "Acción",
    },
    {
        id: 4,
        title: "Toy Story 3",
        rating: 10,
        awards: 2,
        length: 125,
        price: 75,
        genre: "Animación",
    },
    {
        id: 5,
        title: "Laberinto",
        rating: 8,
        awards: 6,
        length: 150,
        price: 50,
        genre: "Aventuras",
    },
    {
        id: 6,
        title: "Star Trek",
        rating: 4,
        awards: 2,
        length: 160,
        price: 45,
        genre: "Ciencia Ficción",
    },
    {
        id: 7,
        title: "Star Wars",
        rating: 8,
        awards: 9,
        length: 160,
        price: 110,
        genre: "Ciencia Ficción",
    },
    {
        id: 8,
        title: "Sexto sentido",
        rating: 9,
        awards: 4,
        length: 125,
        price: 160,
        genre: "Suspenso",
    },
    {
        id: 9,
        title: "The Mask",
        rating: 6,
        awards: 5,
        length: 125,
        price: 80,
        genre: "Comedia",
    },
]
module.exports = movies;